apiVersion: v1
kind: Service
metadata:
  name: shays-app1-service
  labels:
    app: shays-app1
spec:
  type: ClusterIP
  selector:
    app: shays-app1
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 8082