apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: shays-app1
build:
  artifacts:
    - image: shays-app1
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/shays-app1.yaml
    - k8s/service.yaml
    - k8s/servicemonitor.yaml
